# Generated by Django 3.2.8 on 2021-10-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('favoriteProgrammingLanguage', models.CharField(max_length=20)),
                ('activeTaskCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('isDone', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=200)),
                ('dueDate', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_and_people.person')),
            ],
        ),
    ]
