# Generated by Django 3.2.8 on 2021-10-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_and_people', '0003_alter_person_activetaskcount'),
        ('tasks_and_people', '0004_alter_person_activetaskcount'),
    ]

    operations = [
    ]
